- name: scan available networks
  register: src_networks_info

  openstack.cloud.networks_info:
    filters: "{{ os_migrate_src_filters }}"
    auth: "{{ os_migrate_src_auth }}"
    auth_type: "{{ os_migrate_src_auth_type|default(omit) }}"
    region_name: "{{ os_migrate_src_region_name|default(omit) }}"
    validate_certs: "{{ os_migrate_src_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_src_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_src_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_src_client_key|default(omit) }}"
- name: create id-name pairs of networks to export
- name: filter names of networks to export
- name: export network
  loop: "{{ export_networks_ids_names }}"
