-   name: install packages for devstack
    ansible.builtin.package:
      name:
      -   git
      -   python2
      -   python3-devel
      -   tmux
      state: present

-   name: remove packages which devstack does not like
    ansible.builtin.package:
      name:
      -   python3-pyyaml
      state: absent

-   name: create stack user
    ansible.builtin.user:
      name: stack

-   name: create sudoers entry for stack
    ansible.builtin.copy:
      dest: /etc/sudoers.d/stack
      content: |
        stack ALL=(ALL) NOPASSWD:ALL
