- name: scan available routers
  register: src_routers_info

- name: create id-name pairs of routers to export
- name: filter names of routers to export
- name: export router interfaces
  loop: "{{ export_routers_ids_names }}"
