- name: discover conversion host
  register: _server_info

  openstack.cloud.server_info:
    server: "{{ os_migrate_conversion_host_name }}*"
    auth: "{{ os_migrate_conversion_auth }}"
    auth_type: "{{ os_migrate_conversion_auth_type|default(omit) }}"
    region_name: "{{ os_migrate_conversion_region_name|default(omit) }}"
    validate_certs: "{{ os_migrate_conversion_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_conversion_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_conversion_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_conversion_client_key|default(omit) }}"
- name: fail when conversion host was not found
  when:
    - _server_info.openstack_servers|length == 0
    - not ignore_missing_conversion_hosts|default(false)|bool

- name: add conversion host to inventory
  when:
    - _server_info.openstack_servers|length > 0
