-   name: delete os_migrate conversion host
    ansible.builtin.os_server:
      name: "{{ os_migrate_conversion_host_name }}"
      state: absent
      delete_fip: yes
      wait: yes
      auth: "{{ os_migrate_conversion_auth }}"
      auth_type: "{{ os_migrate_conversion_auth_type|default(omit) }}"
      region_name: "{{ os_migrate_conversion_region_name|default(omit) }}"
      validate_certs: "{{ os_migrate_conversion_validate_certs|default(omit) }}"
      ca_cert: "{{ os_migrate_conversion_ca_cert|default(omit) }}"
      client_cert: "{{ os_migrate_conversion_client_cert|default(omit) }}"
      client_key: "{{ os_migrate_conversion_client_key|default(omit) }}"

-   name: delete os_migrate conversion keypair
    ansible.builtin.os_keypair:
      name: "{{ os_migrate_conversion_keypair_name }}"
      state: absent
      auth: "{{ os_migrate_conversion_auth }}"
      auth_type: "{{ os_migrate_conversion_auth_type|default(omit) }}"
      region_name: "{{ os_migrate_conversion_region_name|default(omit) }}"
      validate_certs: "{{ os_migrate_conversion_validate_certs|default(omit) }}"
      ca_cert: "{{ os_migrate_conversion_ca_cert|default(omit) }}"
      client_cert: "{{ os_migrate_conversion_client_cert|default(omit) }}"
      client_key: "{{ os_migrate_conversion_client_key|default(omit) }}"

-   name: delete os_migrate conversion security group
    ansible.builtin.os_security_group:
      name: "{{ os_migrate_conversion_secgroup_name }}"
      state: absent
      auth: "{{ os_migrate_conversion_auth }}"
      auth_type: "{{ os_migrate_conversion_auth_type|default(omit) }}"
      region_name: "{{ os_migrate_conversion_region_name|default(omit) }}"
      validate_certs: "{{ os_migrate_conversion_validate_certs|default(omit) }}"
      ca_cert: "{{ os_migrate_conversion_ca_cert|default(omit) }}"
      client_cert: "{{ os_migrate_conversion_client_cert|default(omit) }}"
      client_key: "{{ os_migrate_conversion_client_key|default(omit) }}"

-   name: delete os_migrate conversion router
    ansible.builtin.os_router:
      name: "{{ os_migrate_conversion_router_name }}"
      state: absent
      auth: "{{ os_migrate_conversion_auth }}"
      auth_type: "{{ os_migrate_conversion_auth_type|default(omit) }}"
      region_name: "{{ os_migrate_conversion_region_name|default(omit) }}"
      validate_certs: "{{ os_migrate_conversion_validate_certs|default(omit) }}"
      ca_cert: "{{ os_migrate_conversion_ca_cert|default(omit) }}"
      client_cert: "{{ os_migrate_conversion_client_cert|default(omit) }}"
      client_key: "{{ os_migrate_conversion_client_key|default(omit) }}"

-   name: delete os_migrate conversion subnet
    ansible.builtin.os_subnet:
      name: "{{ os_migrate_conversion_subnet_name }}"
      state: absent
      auth: "{{ os_migrate_conversion_auth }}"
      auth_type: "{{ os_migrate_conversion_auth_type|default(omit) }}"
      region_name: "{{ os_migrate_conversion_region_name|default(omit) }}"
      validate_certs: "{{ os_migrate_conversion_validate_certs|default(omit) }}"
      ca_cert: "{{ os_migrate_conversion_ca_cert|default(omit) }}"
      client_cert: "{{ os_migrate_conversion_client_cert|default(omit) }}"
      client_key: "{{ os_migrate_conversion_client_key|default(omit) }}"

-   name: delete os_migrate conversion net
    ansible.builtin.os_network:
      name: "{{ os_migrate_conversion_net_name }}"
      state: absent
      auth: "{{ os_migrate_conversion_auth }}"
      auth_type: "{{ os_migrate_conversion_auth_type|default(omit) }}"
      region_name: "{{ os_migrate_conversion_region_name|default(omit) }}"
      validate_certs: "{{ os_migrate_conversion_validate_certs|default(omit) }}"
      ca_cert: "{{ os_migrate_conversion_ca_cert|default(omit) }}"
      client_cert: "{{ os_migrate_conversion_client_cert|default(omit) }}"
      client_key: "{{ os_migrate_conversion_client_key|default(omit) }}"
