- name: create the keypair folder
  ansible.builtin.file:
    path: "{{ os_migrate_conversion_keypair_private_path|dirname }}"
    state: directory

- name: generate a keypair for the conversion host
  ansible.builtin.openssh_keypair:
    path: "{{ os_migrate_conversion_keypair_private_path }}"
