- name: unregister RHEL hosts from RHSM
  vars:
    # Unregistration gets stuck unless we explicitly run the module as root.
    ansible_become: true
    ansible_become_user: root
  when:
  - ansible_distribution is defined
  - ansible_distribution in ['RedHat']
  ansible.builtin.redhat_subscription:
    state: absent
