# NOTE: os_image_info doesn't support os_migrate_src_filters, we apply
# the filters manually below.
- name: scan available images
  register: src_images_info

  openstack.cloud.image_info:
    auth: "{{ os_migrate_src_auth }}"
    auth_type: "{{ os_migrate_src_auth_type|default(omit) }}"
    region_name: "{{ os_migrate_src_region_name|default(omit) }}"
    validate_certs: "{{ os_migrate_src_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_src_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_src_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_src_client_key|default(omit) }}"
- name: create id-name pairs of images to export
- name: filter images to export by project
  when:
    - os_migrate_src_filters is defined
    - os_migrate_src_filters['project_id'] is defined

- name: filter names of images to export
- name: export image metadata
  loop: "{{ export_images_ids_names }}"

- name: make sure image blob dir exists
  when: os_migrate_export_images_blobs

- name: export image blobs
  loop: "{{ export_images_ids_names }}"
  when: os_migrate_export_images_blobs
