- name: validate loaded resources
  register: router_interfaces_file_validation
  when: import_router_interfaces_validate_file

- name: stop when errors found
  when: not ( router_interfaces_file_validation.ok | bool )

- name: read router interfaces resource file
  register: read_router_interfaces

- name: import router interfaces
  loop: "{{ read_router_interfaces.resources }}"
