- name: set os_migrate_src_project unless it was set explicitly
  when:
    - os_migrate_src_filter_current_project|default(true)|bool
  block:
    - name: fetch information about currently authenticated user/project
      register: _auth_info

    - name: set os_migrate_src_project_id and os_migrate_src_filters
