- name: validate loaded resources
  register: workloads_file_validation
  when: import_workloads_validate_file

- name: stop when errors found
  when: not ( workloads_file_validation.ok | bool )

- name: read workloads resource file
  register: read_workloads

- name: create directory for workload migration logs
- name: get source conversion host address
  register: os_src_conversion_host_info

- name: fail if source conversion host is not active
  when: os_src_conversion_host_info.openstack_conversion_host.status != "ACTIVE"

- name: get destination conversion host address
  register: os_dst_conversion_host_info

- name: fail if destination conversion is not active
  when: os_dst_conversion_host_info.openstack_conversion_host.status != "ACTIVE"

# Depending on the virtualization hypervisor,
# the conversion host machines can take too
# much time to start.

- name: Wait until the dst conversion host is reachable
- name: Wait until the src conversion host is reachable
- name: import workloads
  loop: "{{ read_workloads.resources }}"
