- name: scan available security groups
  register: src_security_groups_info

- name: create id-name pairs of security groups to export
- name: filter names of security groups to export
- name: export security groups
  loop: "{{ export_security_groups_ids_names }}"
