- name: validate loaded resources
  register: images_file_validation
  when: import_images_validate_file

- name: stop when errors found
  when: not ( images_file_validation.ok | bool )

- name: read images resource file
  register: read_images

- name: import images
  loop: "{{ read_images.resources }}"
