- name: validate loaded resources
  register: images_file_validation
  when: import_images_validate_file

  ansible.builtin.os_migrate.os_migrate.validate_resource_files:
    paths:
      - "{{ os_migrate_data_dir }}/images.yml"
- name: stop when errors found
  when: not ( images_file_validation.ok | bool )

  ansible.builtin.fail:
    msg: "{{ images_file_validation.errors|join(' ') }}"
- name: read images resource file
  register: read_images

  ansible.builtin.os_migrate.os_migrate.read_resources:
    path: "{{ os_migrate_data_dir }}/images.yml"
- name: import images
  loop: "{{ read_images.resources }}"
  ansible.builtin.os_migrate.os_migrate.import_image:
    auth: "{{ os_migrate_dst_auth }}"
    auth_type: "{{ os_migrate_dst_auth_type|default(omit) }}"
    region_name: "{{ os_migrate_dst_region_name|default(omit) }}"
    data: "{{ item }}"
    blob_path: >-
      {{ os_migrate_image_blobs_dir }}/{{ item['_info']['id'] }}-{{ item['params']['name']
      }}
    filters: "{{ os_migrate_dst_filters }}"
    validate_certs: "{{ os_migrate_dst_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_dst_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_dst_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_dst_client_key|default(omit) }}"
