- name: list resource files
  register: resource_files_result

- when: resource_files_result.files | count < 1

- name: validate resource files
  register: validate_data_dir_result

- name: stop if errors found
  when: not ( validate_data_dir_result.ok | bool )
