-   name: list resource files
    register: resource_files_result

    ansible.builtin.find:
      paths:
      -   "{{ os_migrate_data_dir }}"
      patterns:
      -   "*.yml"
-   when: resource_files_result.files | count < 1

    ansible.builtin.fail:
      msg: No resource files found.
-   name: validate resource files
    register: validate_data_dir_result

    ansible.builtin.os_migrate.os_migrate.validate_resource_files:
      paths: "{{ resource_files_result.files | map(attribute='path') | list }}"
-   name: stop if errors found
    when: not ( validate_data_dir_result.ok | bool )
    ansible.builtin.fail:
      msg: "{{ validate_data_dir_result.errors | join(' ') }}"
