- name: validate loaded resources
  os_migrate.os_migrate.validate_resource_files:
    paths:
      - "{{ os_migrate_data_dir }}/users.yml"
  register: users_file_validation
  when: import_users_validate_file

- name: stop when errors found
  fail:
    msg: "{{ users_file_validation.errors|join(' ') }}"
  when: not ( users_file_validation.ok | bool )

- name: read users resource file
  os_migrate.os_migrate.read_resources:
    path: "{{ os_migrate_data_dir }}/users.yml"
  register: read_users

- name: import users
  os_migrate.os_migrate.import_user:
    auth: "{{ os_migrate_dst_auth }}"
    auth_type: "{{ os_migrate_dst_auth_type|default(omit) }}"
    region_name: "{{ os_migrate_dst_region_name|default(omit) }}"
    data: "{{ item }}"
    validate_certs: "{{ os_migrate_dst_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_dst_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_dst_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_dst_client_key|default(omit) }}"
  loop: "{{ read_users.resources }}"
