- name: validate loaded resources
  register: users_file_validation
  when: import_users_validate_file

- name: stop when errors found
  when: not ( users_file_validation.ok | bool )

- name: read users resource file
  register: read_users

- name: import users
  loop: "{{ read_users.resources }}"
