- hosts: migrator
  tasks:
    - vars:
        ignore_missing_conversion_hosts: true

- hosts: conversion_hosts
# Unregistration is best-effort. If the conversion hosts faced some
# issues and are unreachable, we don't want the host deletion to
# fail too.
  ignore_unreachable: true
  tasks:
    - {}
- hosts: migrator
  tasks:
    - vars:
        os_migrate_conversion_auth: "{{ os_migrate_src_auth }}"
        os_migrate_conversion_auth_type: "{{ os_migrate_src_auth_type|default(omit) }}"
        os_migrate_conversion_region_name: "{{ os_migrate_src_region_name|default(omit) }}"
        os_migrate_conversion_validate_certs: "{{ os_migrate_src_validate_certs|default(omit) }}"
        os_migrate_conversion_ca_cert: "{{ os_migrate_src_ca_cert|default(omit) }}"
        os_migrate_conversion_client_cert: "{{ os_migrate_src_client_cert|default(omit) }}"
        os_migrate_conversion_client_key: "{{ os_migrate_src_client_key|default(omit) }}"
      when: os_migrate_delete_src_conversion_host|default(true)|bool

    - vars:
        os_migrate_conversion_auth: "{{ os_migrate_dst_auth }}"
        os_migrate_conversion_auth_type: "{{ os_migrate_dst_auth_type|default(omit) }}"
        os_migrate_conversion_region_name: "{{ os_migrate_dst_region_name|default(omit) }}"
        os_migrate_conversion_validate_certs: "{{ os_migrate_dst_validate_certs|default(omit) }}"
        os_migrate_conversion_ca_cert: "{{ os_migrate_dst_ca_cert|default(omit) }}"
        os_migrate_conversion_client_cert: "{{ os_migrate_dst_client_cert|default(omit) }}"
        os_migrate_conversion_client_key: "{{ os_migrate_dst_client_key|default(omit) }}"
      when: os_migrate_delete_dst_conversion_host|default(true)|bool
