- hosts: migrator
  tasks:
  - vars:
      os_migrate_conversion_auth: "{{ os_migrate_src_auth }}"
      os_migrate_conversion_auth_type: "{{ os_migrate_src_auth_type|default(omit)\
        \ }}"
      os_migrate_conversion_region_name: "{{ os_migrate_src_region_name|default(omit)\
        \ }}"
      os_migrate_conversion_validate_certs: "{{ os_migrate_src_validate_certs|default(omit)\
        \ }}"
      os_migrate_conversion_ca_cert: "{{ os_migrate_src_ca_cert|default(omit) }}"
      os_migrate_conversion_client_cert: "{{ os_migrate_src_client_cert|default(omit)\
        \ }}"
      os_migrate_conversion_client_key: "{{ os_migrate_src_client_key|default(omit)\
        \ }}"
      os_migrate_conversion_flavor_name: "{{ os_migrate_src_conversion_flavor_name|default(omit)\
        \ }}"
      os_migrate_conversion_image_name: "{{ os_migrate_src_conversion_image_name|default(omit)\
        \ }}"
      os_migrate_conversion_external_network_name: "{{ os_migrate_src_conversion_external_network_name\
        \ }}"
      os_migrate_conversion_net_mtu: "{{ os_migrate_src_conversion_net_mtu|default(omit)\
        \ }}"
      os_migrate_conversion_subnet_dns_nameservers: "{{ os_migrate_src_conversion_subnet_dns_nameservers|default(omit)\
        \ }}"
    when: os_migrate_deploy_src_conversion_host|default(true)|bool

    ansible.builtin.include_role:
      name: os_migrate.os_migrate.conversion_host
  - vars:
      os_migrate_conversion_auth: "{{ os_migrate_dst_auth }}"
      os_migrate_conversion_auth_type: "{{ os_migrate_dst_auth_type|default(omit)\
        \ }}"
      os_migrate_conversion_region_name: "{{ os_migrate_dst_region_name|default(omit)\
        \ }}"
      os_migrate_conversion_validate_certs: "{{ os_migrate_dst_validate_certs|default(omit)\
        \ }}"
      os_migrate_conversion_ca_cert: "{{ os_migrate_dst_ca_cert|default(omit) }}"
      os_migrate_conversion_client_cert: "{{ os_migrate_dst_client_cert|default(omit)\
        \ }}"
      os_migrate_conversion_client_key: "{{ os_migrate_dst_client_key|default(omit)\
        \ }}"
      os_migrate_conversion_flavor_name: "{{ os_migrate_dst_conversion_flavor_name|default(omit)\
        \ }}"
      os_migrate_conversion_image_name: "{{ os_migrate_dst_conversion_image_name|default(omit)\
        \ }}"
      os_migrate_conversion_external_network_name: "{{ os_migrate_dst_conversion_external_network_name\
        \ }}"
      os_migrate_conversion_net_mtu: "{{ os_migrate_dst_conversion_net_mtu|default(omit)\
        \ }}"
      os_migrate_conversion_subnet_dns_nameservers: "{{ os_migrate_dst_conversion_subnet_dns_nameservers|default(omit)\
        \ }}"
    when: os_migrate_deploy_dst_conversion_host|default(true)|bool

    ansible.builtin.include_role:
      name: os_migrate.os_migrate.conversion_host
  - when: os_migrate_link_conversion_hosts|default(true)|bool

    ansible.builtin.include_role:
      name: os_migrate.os_migrate.conversion_host
      tasks_from: link_prepare.yml
- hosts: os_migrate_conv_src
  tasks:
  - when: os_migrate_link_conversion_hosts|default(true)|bool

    ansible.builtin.include_role:
      name: os_migrate.os_migrate.conversion_host
      tasks_from: link_insert_authorized_key.yml
- hosts: os_migrate_conv_dst
  tasks:
  - when: os_migrate_link_conversion_hosts|default(true)|bool

    ansible.builtin.include_role:
      name: os_migrate.os_migrate.conversion_host
      tasks_from: link_insert_private_key.yml
- hosts: conversion_hosts
  tasks:
  - when: os_migrate_conversion_host_content_install|default(true)|bool
    ansible.builtin.include_role:
      name: os_migrate.os_migrate.conversion_host_content
  vars:
    ansible_become_user: root
    ansible_become: true
