- name: validate loaded resources
  register: routers_file_validation
  when: import_routers_validate_file

- name: stop when errors found
  when: not ( routers_file_validation.ok | bool )

- name: read routers resource file
  register: read_routers

- name: import routers
  loop: "{{ read_routers.resources }}"
