- name: validate loaded resources
  register: networks_file_validation
  when: import_networks_validate_file

  ansible.builtin.os_migrate.os_migrate.validate_resource_files:
    paths:
      - "{{ os_migrate_data_dir }}/networks.yml"
- name: stop when errors found
  when: not ( networks_file_validation.ok | bool )

  ansible.builtin.fail:
    msg: "{{ networks_file_validation.errors|join(' ') }}"
- name: read networks resource file
  register: read_networks

  ansible.builtin.os_migrate.os_migrate.read_resources:
    path: "{{ os_migrate_data_dir }}/networks.yml"
- name: import networks
  loop: "{{ read_networks.resources }}"
  ansible.builtin.os_migrate.os_migrate.import_network:
    auth: "{{ os_migrate_dst_auth }}"
    auth_type: "{{ os_migrate_dst_auth_type|default(omit) }}"
    region_name: "{{ os_migrate_dst_region_name|default(omit) }}"
    data: "{{ item }}"
    filters: "{{ os_migrate_dst_filters }}"
    validate_certs: "{{ os_migrate_dst_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_dst_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_dst_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_dst_client_key|default(omit) }}"
