- name: validate loaded resources
  register: networks_file_validation
  when: import_networks_validate_file

- name: stop when errors found
  when: not ( networks_file_validation.ok | bool )

- name: read networks resource file
  register: read_networks

- name: import networks
  loop: "{{ read_networks.resources }}"
