- name: validate loaded resources
  register: keypairs_file_validation
  when: import_keypairs_validate_file

- name: stop when errors found
  when: not ( keypairs_file_validation.ok | bool )

- name: read keypairs resource file
  register: read_keypairs

- name: import keypairs
  loop: "{{ read_keypairs.resources }}"
