- name: validate loaded resources
  register: keypairs_file_validation
  when: import_keypairs_validate_file

  ansible.builtin.os_migrate.os_migrate.validate_resource_files:
    paths:
    - "{{ os_migrate_data_dir }}/keypairs.yml"
- name: stop when errors found
  when: not ( keypairs_file_validation.ok | bool )

  ansible.builtin.fail:
    msg: "{{ keypairs_file_validation.errors|join(' ') }}"
- name: read keypairs resource file
  register: read_keypairs

  ansible.builtin.os_migrate.os_migrate.read_resources:
    path: "{{ os_migrate_data_dir }}/keypairs.yml"
- name: import keypairs
  loop: "{{ read_keypairs.resources }}"
  ansible.builtin.os_migrate.os_migrate.import_keypair:
    auth: "{{ os_migrate_dst_auth }}"
    auth_type: "{{ os_migrate_dst_auth_type|default(omit) }}"
    region_name: "{{ os_migrate_dst_region_name|default(omit) }}"
    data: "{{ item }}"
    validate_certs: "{{ os_migrate_dst_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_dst_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_dst_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_dst_client_key|default(omit) }}"
